/**
 * TabChroma - Preset URL Rule Packs (Strictly Generic Dummy / Example Rules)
 * Generic dummy patterns using example.com, example.org, example.net, localhost.
 */

import { TabColorRule } from '../types/extension';

export interface PresetPack {
  id: string;
  name: string;
  description: string;
  icon: string;
  badge: string;
  category: 'workflow' | 'demo';
  tags: string[];
  rules: TabColorRule[];
}

export const DEVELOPMENT_RULES: TabColorRule[] = [
  {
    id: 'pack-dev-github',
    name: 'GitHub (Code & Repos)',
    patternType: 'domain',
    pattern: 'github.com',
    color: '#9059ff',
    firefoxContainerColor: 'purple',
    firefoxContainerIcon: 'briefcase',
    customEmoji: '⚡',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'GitHub / Code',
    colorMode: 'container',
    accentBorder: true,
    enabled: true,
    priority: 1,
  },
  {
    id: 'pack-dev-gitlab',
    name: 'GitLab (CI/CD Pipelines)',
    patternType: 'domain',
    pattern: 'gitlab.com',
    color: '#ff9400',
    firefoxContainerColor: 'orange',
    firefoxContainerIcon: 'tree',
    customEmoji: '🦊',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'GitLab / CI',
    colorMode: 'container',
    accentBorder: true,
    enabled: true,
    priority: 2,
  },
  {
    id: 'pack-dev-localhost',
    name: 'Localhost & Dev Servers',
    patternType: 'wildcard',
    pattern: 'localhost:*',
    color: '#51cf66',
    firefoxContainerColor: 'green',
    firefoxContainerIcon: 'tree',
    customEmoji: '💻',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'Localhost / Dev',
    colorMode: 'container',
    accentBorder: true,
    enabled: true,
    priority: 3,
  },
  {
    id: 'pack-dev-staging',
    name: 'Staging & Test Environments',
    patternType: 'wildcard',
    pattern: '*.staging.*',
    color: '#00c79a',
    firefoxContainerColor: 'turquoise',
    firefoxContainerIcon: 'circle',
    customEmoji: '🧪',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'Staging / Test',
    colorMode: 'container',
    accentBorder: true,
    enabled: true,
    priority: 4,
  },
  {
    id: 'pack-dev-cloud',
    name: 'Cloud Console & Production',
    patternType: 'wildcard',
    pattern: '*console.cloud.google.com*',
    color: '#ff4f5e',
    firefoxContainerColor: 'red',
    firefoxContainerIcon: 'fingerprint',
    customEmoji: '🚀',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'Cloud Production',
    colorMode: 'container',
    accentBorder: true,
    enabled: true,
    priority: 5,
  },
  {
    id: 'pack-dev-docs',
    name: 'Developer Docs (MDN & StackOverflow)',
    patternType: 'domain',
    pattern: 'developer.mozilla.org',
    color: '#ffcb00',
    firefoxContainerColor: 'yellow',
    firefoxContainerIcon: 'chill',
    customEmoji: '📚',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'Dev Documentation',
    colorMode: 'container',
    accentBorder: true,
    enabled: true,
    priority: 6,
  },
];

export const SOCIAL_RULES: TabColorRule[] = [
  {
    id: 'pack-soc-twitter',
    name: 'X / Twitter',
    patternType: 'domain',
    pattern: 'x.com',
    color: '#37adff',
    firefoxContainerColor: 'blue',
    firefoxContainerIcon: 'circle',
    customEmoji: '🐦',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'X / Twitter',
    colorMode: 'container',
    accentBorder: true,
    enabled: true,
    priority: 1,
  },
  {
    id: 'pack-soc-reddit',
    name: 'Reddit Community',
    patternType: 'domain',
    pattern: 'reddit.com',
    color: '#ff9400',
    firefoxContainerColor: 'orange',
    firefoxContainerIcon: 'circle',
    customEmoji: '🤖',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'Reddit',
    colorMode: 'container',
    accentBorder: true,
    enabled: true,
    priority: 2,
  },
  {
    id: 'pack-soc-linkedin',
    name: 'LinkedIn Professional Network',
    patternType: 'domain',
    pattern: 'linkedin.com',
    color: '#37adff',
    firefoxContainerColor: 'blue',
    firefoxContainerIcon: 'briefcase',
    customEmoji: '💼',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'LinkedIn',
    colorMode: 'container',
    accentBorder: true,
    enabled: true,
    priority: 3,
  },
  {
    id: 'pack-soc-youtube',
    name: 'YouTube Media & Streams',
    patternType: 'domain',
    pattern: 'youtube.com',
    color: '#ff4f5e',
    firefoxContainerColor: 'red',
    firefoxContainerIcon: 'chill',
    customEmoji: '▶️',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'YouTube',
    colorMode: 'container',
    accentBorder: true,
    enabled: true,
    priority: 4,
  },
  {
    id: 'pack-soc-discord',
    name: 'Discord Communities & Chat',
    patternType: 'domain',
    pattern: 'discord.com',
    color: '#9059ff',
    firefoxContainerColor: 'purple',
    firefoxContainerIcon: 'chill',
    customEmoji: '💬',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'Discord',
    colorMode: 'container',
    accentBorder: true,
    enabled: true,
    priority: 5,
  },
  {
    id: 'pack-soc-instagram',
    name: 'Instagram & Threads',
    patternType: 'domain',
    pattern: 'instagram.com',
    color: '#ff4ba0',
    firefoxContainerColor: 'pink',
    firefoxContainerIcon: 'circle',
    customEmoji: '📸',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'Instagram',
    colorMode: 'container',
    accentBorder: true,
    enabled: true,
    priority: 6,
  },
];

export const SHOPPING_RULES: TabColorRule[] = [
  {
    id: 'pack-shop-amazon',
    name: 'Amazon Online Shopping',
    patternType: 'wildcard',
    pattern: '*amazon.*',
    color: '#ff9400',
    firefoxContainerColor: 'orange',
    firefoxContainerIcon: 'cart',
    customEmoji: '🛒',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'Amazon Shopping',
    colorMode: 'container',
    accentBorder: true,
    enabled: true,
    priority: 1,
  },
  {
    id: 'pack-shop-ebay',
    name: 'eBay Marktplatz',
    patternType: 'wildcard',
    pattern: '*ebay.*',
    color: '#37adff',
    firefoxContainerColor: 'blue',
    firefoxContainerIcon: 'cart',
    customEmoji: '🛍️',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'eBay',
    colorMode: 'container',
    accentBorder: true,
    enabled: true,
    priority: 2,
  },
  {
    id: 'pack-shop-paypal',
    name: 'PayPal & Checkout',
    patternType: 'domain',
    pattern: 'paypal.com',
    color: '#ffcb00',
    firefoxContainerColor: 'yellow',
    firefoxContainerIcon: 'dollar',
    customEmoji: '💳',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'PayPal / Checkout',
    colorMode: 'container',
    accentBorder: true,
    enabled: true,
    priority: 3,
  },
  {
    id: 'pack-shop-banking',
    name: 'Online Banking & Finanzen',
    patternType: 'wildcard',
    pattern: '*banking.*',
    color: '#51cf66',
    firefoxContainerColor: 'green',
    firefoxContainerIcon: 'dollar',
    customEmoji: '🏦',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'Banking & Finanzen',
    colorMode: 'container',
    accentBorder: true,
    enabled: true,
    priority: 4,
  },
  {
    id: 'pack-shop-etsy',
    name: 'Etsy & Handgemachtes',
    patternType: 'domain',
    pattern: 'etsy.com',
    color: '#ff4ba0',
    firefoxContainerColor: 'pink',
    firefoxContainerIcon: 'gift',
    customEmoji: '🎁',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'Etsy Shopping',
    colorMode: 'container',
    accentBorder: true,
    enabled: true,
    priority: 5,
  },
];

export const WORK_RULES: TabColorRule[] = [
  {
    id: 'pack-work-gsuite',
    name: 'Google Workspace (Docs & Drive)',
    patternType: 'wildcard',
    pattern: '*.google.com/document*',
    color: '#37adff',
    firefoxContainerColor: 'blue',
    firefoxContainerIcon: 'briefcase',
    customEmoji: '📂',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'Google Workspace',
    colorMode: 'container',
    accentBorder: true,
    enabled: true,
    priority: 1,
  },
  {
    id: 'pack-work-jira',
    name: 'Jira & Confluence (Atlassian)',
    patternType: 'wildcard',
    pattern: '*.atlassian.net*',
    color: '#00c79a',
    firefoxContainerColor: 'turquoise',
    firefoxContainerIcon: 'briefcase',
    customEmoji: '🎯',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'Jira / Confluence',
    colorMode: 'container',
    accentBorder: true,
    enabled: true,
    priority: 2,
  },
  {
    id: 'pack-work-slack',
    name: 'Slack Team Collaboration',
    patternType: 'wildcard',
    pattern: '*.slack.com*',
    color: '#9059ff',
    firefoxContainerColor: 'purple',
    firefoxContainerIcon: 'briefcase',
    customEmoji: '💬',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'Slack Team',
    colorMode: 'container',
    accentBorder: true,
    enabled: true,
    priority: 3,
  },
  {
    id: 'pack-work-mail',
    name: 'Webmail & Outlook Office',
    patternType: 'domain',
    pattern: 'mail.google.com',
    color: '#ff4f5e',
    firefoxContainerColor: 'red',
    firefoxContainerIcon: 'briefcase',
    customEmoji: '✉️',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'Business Mail',
    colorMode: 'container',
    accentBorder: true,
    enabled: true,
    priority: 4,
  },
  {
    id: 'pack-work-notion',
    name: 'Notion Workspace',
    patternType: 'domain',
    pattern: 'notion.so',
    color: '#ffcb00',
    firefoxContainerColor: 'yellow',
    firefoxContainerIcon: 'circle',
    customEmoji: '📝',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'Notion Docs',
    colorMode: 'container',
    accentBorder: true,
    enabled: true,
    priority: 5,
  },
];

export const PRIVACY_RULES: TabColorRule[] = [
  {
    id: 'pack-priv-auth',
    name: 'Kritisches SSO & Login',
    patternType: 'wildcard',
    pattern: '*login.*',
    color: '#ff4f5e',
    firefoxContainerColor: 'red',
    firefoxContainerIcon: 'fingerprint',
    customEmoji: '🔒',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'Isolierte Auth',
    colorMode: 'container',
    accentBorder: true,
    enabled: true,
    priority: 1,
  },
  {
    id: 'pack-priv-search',
    name: 'Private Suche (DuckDuckGo)',
    patternType: 'domain',
    pattern: 'duckduckgo.com',
    color: '#ff9400',
    firefoxContainerColor: 'orange',
    firefoxContainerIcon: 'circle',
    customEmoji: '🕵️',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'Private Suche',
    colorMode: 'container',
    accentBorder: true,
    enabled: true,
    priority: 2,
  },
  {
    id: 'pack-priv-sandbox',
    name: 'Untrusted Sandbox Isolation',
    patternType: 'wildcard',
    pattern: '*.temp.*',
    color: '#ff4ba0',
    firefoxContainerColor: 'pink',
    firefoxContainerIcon: 'circle',
    customEmoji: '☣️',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'Untrusted Sandbox',
    colorMode: 'container',
    accentBorder: true,
    enabled: true,
    priority: 3,
  },
];

export const DUMMY_RULES: TabColorRule[] = [
  {
    id: 'dummy-prod',
    name: 'Production Environment',
    patternType: 'domain',
    pattern: 'prod.example.com',
    color: '#ff4f5e',
    firefoxContainerColor: 'red',
    firefoxContainerIcon: 'circle',
    customEmoji: '🚀',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'PROD (Beispiel)',
    colorMode: 'container',
    accentBorder: true,
    enabled: true,
    priority: 1,
  },
  {
    id: 'dummy-import',
    name: 'Import Service',
    patternType: 'exact_host',
    pattern: 'import.example.com',
    color: '#37adff',
    firefoxContainerColor: 'blue',
    firefoxContainerIcon: 'briefcase',
    customEmoji: '⬇️',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'Import (Beispiel)',
    colorMode: 'container',
    accentBorder: true,
    enabled: true,
    priority: 2,
  },
  {
    id: 'dummy-staging',
    name: 'Staging Test',
    patternType: 'wildcard',
    pattern: '*.staging.example.org/*',
    color: '#ff9400',
    firefoxContainerColor: 'orange',
    firefoxContainerIcon: 'cart',
    customEmoji: '🧪',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'Staging (Beispiel)',
    colorMode: 'container',
    accentBorder: true,
    enabled: true,
    priority: 3,
  },
  {
    id: 'dummy-dev',
    name: 'Localhost Dev Server',
    patternType: 'wildcard',
    pattern: 'localhost:*',
    color: '#51cf66',
    firefoxContainerColor: 'green',
    firefoxContainerIcon: 'tree',
    customEmoji: '⚡',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'Localhost (Beispiel)',
    colorMode: 'container',
    accentBorder: true,
    enabled: true,
    priority: 4,
  },
];

export const PRESET_PACKS: PresetPack[] = [
  {
    id: 'workflow-development',
    name: 'Development & DevOps',
    description: 'GitHub, GitLab, Localhost, Staging, Cloud Console & Dev Docs sauber in Entwicklungs-Containern getrennt.',
    icon: '💻',
    badge: 'Empfohlen',
    category: 'workflow',
    tags: ['github.com', 'gitlab.com', 'localhost:*', 'staging', 'cloud'],
    rules: DEVELOPMENT_RULES,
  },
  {
    id: 'workflow-social',
    name: 'Social Media & Community',
    description: 'X / Twitter, Reddit, LinkedIn, YouTube, Discord & Instagram vor Cross-Site-Tracking isolieren.',
    icon: '💬',
    badge: 'Tracking-Schutz',
    category: 'workflow',
    tags: ['x.com', 'reddit.com', 'linkedin.com', 'youtube.com', 'discord.com'],
    rules: SOCIAL_RULES,
  },
  {
    id: 'workflow-shopping',
    name: 'Shopping & Finanzen',
    description: 'Amazon, eBay, PayPal, Online-Banking und Zahlungsdienstleister in sicheren Einkaufs-Containern bündeln.',
    icon: '🛒',
    badge: 'Sicherheit',
    category: 'workflow',
    tags: ['amazon.*', 'ebay.*', 'paypal.com', 'banking', 'etsy.com'],
    rules: SHOPPING_RULES,
  },
  {
    id: 'workflow-work',
    name: 'Work & Productivity',
    description: 'Google Workspace, Jira/Confluence, Slack, Business-Webmail & Notion isoliert vom privaten Browsen.',
    icon: '📂',
    badge: 'Produktivität',
    category: 'workflow',
    tags: ['google.com', 'atlassian.net', 'slack.com', 'outlook', 'notion.so'],
    rules: WORK_RULES,
  },
  {
    id: 'workflow-privacy',
    name: 'Privacy & Sandbox',
    description: 'Isolierte Anmeldedienste (SSO/Auth), private Suchmaschinen und ungetestete Sandbox-Websites.',
    icon: '🔒',
    badge: 'Datenschutz',
    category: 'workflow',
    tags: ['login.*', 'duckduckgo.com', 'temp.sandbox'],
    rules: PRIVACY_RULES,
  },
  {
    id: 'dummy-standard',
    name: 'Standard DevOps (Beispiel)',
    description: 'Generische Muster mit beispielhaften Domains (prod, import, staging, localhost).',
    icon: '🧪',
    badge: 'Beispiel',
    category: 'demo',
    tags: ['prod.example.com', 'import.example.com', 'staging.example.org', 'localhost'],
    rules: DUMMY_RULES,
  },
];
