/**
 * TabChroma - Preset URL Rule Packs (Strictly Generic Dummy / Example Rules)
 * Generic dummy patterns using example.com, example.org, example.net, localhost.
 */

import { TabColorRule } from '../types/extension';

export interface PresetPack {
  id: string;
  name: string;
  description: string;
  rules: TabColorRule[];
}

export const DUMMY_RULES: TabColorRule[] = [
  {
    id: 'dummy-prod',
    name: 'Dummy: Production Example',
    patternType: 'domain',
    pattern: 'prod.example.com',
    color: '#ff4f5e',
    firefoxContainerColor: 'red',
    firefoxContainerIcon: 'circle',
    customEmoji: '🚀',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'PROD (Beispiel)',
    colorMode: 'hybrid',
    accentBorder: true,
    enabled: true,
    priority: 1,
  },
  {
    id: 'dummy-import',
    name: 'Dummy: Import Service Example',
    patternType: 'exact_host',
    pattern: 'import.example.com',
    color: '#37adff',
    firefoxContainerColor: 'blue',
    firefoxContainerIcon: 'briefcase',
    customEmoji: '⬇️',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'Import (Beispiel)',
    colorMode: 'hybrid',
    accentBorder: true,
    enabled: true,
    priority: 2,
  },
  {
    id: 'dummy-staging',
    name: 'Dummy: Staging Test Example',
    patternType: 'wildcard',
    pattern: '*.staging.example.org/*',
    color: '#ff9400',
    firefoxContainerColor: 'orange',
    firefoxContainerIcon: 'cart',
    customEmoji: '🧪',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'Staging (Beispiel)',
    colorMode: 'hybrid',
    accentBorder: true,
    enabled: true,
    priority: 3,
  },
  {
    id: 'dummy-dev',
    name: 'Dummy: Localhost Dev Example',
    patternType: 'wildcard',
    pattern: 'localhost:*',
    color: '#51cf66',
    firefoxContainerColor: 'green',
    firefoxContainerIcon: 'tree',
    customEmoji: '⚡',
    enableTitleEmoji: true,
    enableFaviconEmoji: true,
    containerName: 'Localhost (Beispiel)',
    colorMode: 'hybrid',
    accentBorder: true,
    enabled: true,
    priority: 4,
  },
];

export const PRESET_PACKS: PresetPack[] = [
  {
    id: 'dummy-standard',
    name: 'Standard Dummy Rules (Beispiel-Regeln)',
    description: 'Generische Muster mit beispielhaften Domains (prod, import, staging, localhost).',
    rules: DUMMY_RULES,
  },
  {
    id: 'dummy-colors',
    name: 'Farbcodierte Muster (Farben-Demo)',
    description: 'Einfache Farbzuweisungen für red.example.net bis yellow.example.net.',
    rules: [
      {
        id: 'dummy-col-red',
        name: 'Demo Rot (Kritisch)',
        patternType: 'domain',
        pattern: 'red.example.net',
        color: '#ff4f5e',
        firefoxContainerColor: 'red',
        firefoxContainerIcon: 'circle',
        customEmoji: '🔴',
        enableTitleEmoji: true,
        enableFaviconEmoji: true,
        containerName: 'Rot Demo',
        colorMode: 'hybrid',
        accentBorder: true,
        enabled: true,
        priority: 1,
      },
      {
        id: 'dummy-col-blue',
        name: 'Demo Blau (Import/Work)',
        patternType: 'domain',
        pattern: 'blue.example.net',
        color: '#37adff',
        firefoxContainerColor: 'blue',
        firefoxContainerIcon: 'briefcase',
        customEmoji: '⬇️',
        enableTitleEmoji: true,
        enableFaviconEmoji: true,
        containerName: 'Blau Demo',
        colorMode: 'hybrid',
        accentBorder: true,
        enabled: true,
        priority: 2,
      },
      {
        id: 'dummy-col-green',
        name: 'Demo Grün (Sicher/Dev)',
        patternType: 'domain',
        pattern: 'green.example.net',
        color: '#51cf66',
        firefoxContainerColor: 'green',
        firefoxContainerIcon: 'tree',
        customEmoji: '🟢',
        enableTitleEmoji: true,
        enableFaviconEmoji: true,
        containerName: 'Grün Demo',
        colorMode: 'hybrid',
        accentBorder: true,
        enabled: true,
        priority: 3,
      },
      {
        id: 'dummy-col-yellow',
        name: 'Demo Gelb (Warnung/Finanzen)',
        patternType: 'domain',
        pattern: 'yellow.example.net',
        color: '#ffcb00',
        firefoxContainerColor: 'yellow',
        firefoxContainerIcon: 'dollar',
        customEmoji: '🟡',
        enableTitleEmoji: true,
        enableFaviconEmoji: true,
        containerName: 'Gelb Demo',
        colorMode: 'hybrid',
        accentBorder: true,
        enabled: true,
        priority: 4,
      },
    ],
  },
];
