/**
 * TabChroma - Preset URL Rule Packs
 */

import { TabColorRule } from '../types/extension';

export interface PresetPack {
  id: string;
  name: string;
  description: string;
  rules: TabColorRule[];
}

export const PRESET_PACKS: PresetPack[] = [
  {
    id: 'devops-environments',
    name: 'DevOps & Environments',
    description: 'Distinct safety colors for Production, Staging, Localhost, and Cloud Consoles.',
    rules: [
      {
        id: 'rule-prod',
        name: 'Production Environments',
        patternType: 'regex',
        pattern: '(prod|production|live)\\.([a-z0-9-]+\\.)*(com|io|net|org)|aws\\.amazon\\.com',
        color: '#ff4f5e',
        firefoxContainerColor: 'red',
        firefoxContainerIcon: 'circle',
        containerName: 'PROD (High Alert)',
        colorMode: 'hybrid',
        accentBorder: true,
        enabled: true,
        priority: 1,
      },
      {
        id: 'rule-staging',
        name: 'Staging & Pre-release',
        patternType: 'wildcard',
        pattern: '*staging*.*',
        color: '#ff9400',
        firefoxContainerColor: 'orange',
        firefoxContainerIcon: 'briefcase',
        containerName: 'Staging Env',
        colorMode: 'hybrid',
        accentBorder: true,
        enabled: true,
        priority: 2,
      },
      {
        id: 'rule-local',
        name: 'Localhost & Dev Servers',
        patternType: 'regex',
        pattern: 'https?:\\/\\/(localhost|127\\.0\\.0\\.1|0\\.0\\.0\\.0)(:\\d+)?.*',
        color: '#51cf66',
        firefoxContainerColor: 'green',
        firefoxContainerIcon: 'tree',
        containerName: 'Localhost Dev',
        colorMode: 'hybrid',
        accentBorder: true,
        enabled: true,
        priority: 3,
      },
      {
        id: 'rule-repos',
        name: 'Code Repositories (GitHub/GitLab)',
        patternType: 'domain',
        pattern: 'github.com',
        color: '#37adff',
        firefoxContainerColor: 'blue',
        firefoxContainerIcon: 'fingerprint',
        containerName: 'Git Repositories',
        colorMode: 'container',
        accentBorder: true,
        enabled: true,
        priority: 4,
      },
    ],
  },
  {
    id: 'work-life-balance',
    name: 'Work vs Personal',
    description: 'Separate business SaaS tools from social, streaming, and personal reading.',
    rules: [
      {
        id: 'rule-work-workspace',
        name: 'Work Workspace (Google/Slack/Jira)',
        patternType: 'regex',
        pattern: '(slack\\.com|atlassian\\.net|jira|notion\\.so|linear\\.app)',
        color: '#37adff',
        firefoxContainerColor: 'blue',
        firefoxContainerIcon: 'briefcase',
        containerName: 'Work Projects',
        colorMode: 'hybrid',
        accentBorder: true,
        enabled: true,
        priority: 1,
      },
      {
        id: 'rule-finance',
        name: 'Banking & Financial Portals',
        patternType: 'regex',
        pattern: '(bank|chase\\.com|paypal\\.com|stripe\\.com|fidelity\\.com)',
        color: '#ffcb00',
        firefoxContainerColor: 'yellow',
        firefoxContainerIcon: 'dollar',
        containerName: 'Secure Finance',
        colorMode: 'hybrid',
        accentBorder: true,
        enabled: true,
        priority: 2,
      },
      {
        id: 'rule-shopping',
        name: 'E-Commerce & Orders',
        patternType: 'regex',
        pattern: '(amazon\\.com|ebay\\.com|etsy\\.com|shopify\\.com)',
        color: '#ff9400',
        firefoxContainerColor: 'orange',
        firefoxContainerIcon: 'cart',
        containerName: 'Shopping',
        colorMode: 'container',
        accentBorder: false,
        enabled: true,
        priority: 3,
      },
      {
        id: 'rule-personal',
        name: 'Social & Media (Reddit/YouTube)',
        patternType: 'regex',
        pattern: '(youtube\\.com|reddit\\.com|twitter\\.com|x\\.com|netflix\\.com)',
        color: '#ff4ba0',
        firefoxContainerColor: 'pink',
        firefoxContainerIcon: 'chill',
        containerName: 'Leisure & Media',
        colorMode: 'hybrid',
        accentBorder: true,
        enabled: true,
        priority: 4,
      },
    ],
  },
  {
    id: 'cloud-infrastructure',
    name: 'Multi-Cloud Consoles',
    description: 'Dedicated color containers for AWS, Google Cloud, Microsoft Azure, and Cloudflare.',
    rules: [
      {
        id: 'rule-aws',
        name: 'Amazon Web Services (AWS)',
        patternType: 'domain',
        pattern: 'console.aws.amazon.com',
        color: '#ff9400',
        firefoxContainerColor: 'orange',
        firefoxContainerIcon: 'briefcase',
        containerName: 'AWS Cloud',
        colorMode: 'hybrid',
        accentBorder: true,
        enabled: true,
        priority: 1,
      },
      {
        id: 'rule-gcp',
        name: 'Google Cloud Platform (GCP)',
        patternType: 'domain',
        pattern: 'console.cloud.google.com',
        color: '#37adff',
        firefoxContainerColor: 'blue',
        firefoxContainerIcon: 'circle',
        containerName: 'GCP Cloud',
        colorMode: 'hybrid',
        accentBorder: true,
        enabled: true,
        priority: 2,
      },
      {
        id: 'rule-azure',
        name: 'Microsoft Azure Portal',
        patternType: 'domain',
        pattern: 'portal.azure.com',
        color: '#00c79a',
        firefoxContainerColor: 'turquoise',
        firefoxContainerIcon: 'circle',
        containerName: 'Azure Cloud',
        colorMode: 'hybrid',
        accentBorder: true,
        enabled: true,
        priority: 3,
      },
      {
        id: 'rule-cloudflare',
        name: 'Cloudflare Dashboard',
        patternType: 'domain',
        pattern: 'dash.cloudflare.com',
        color: '#ff4f5e',
        firefoxContainerColor: 'red',
        firefoxContainerIcon: 'fingerprint',
        containerName: 'Cloudflare Edge',
        colorMode: 'hybrid',
        accentBorder: true,
        enabled: true,
        priority: 4,
      },
    ],
  },
];
